version: "3.8"

services:
  database-test:
    container_name: postgres-test
    image: postgres:15.0-alpine
    environment:
      POSTGRES_USER: boris
      POSTGRES_PASSWORD: 12345
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5433:5432

  hoverfly-test:
    container_name: hoverfly-test
    image: spectolabs/hoverfly:v1.3.4
    command:
      # у Ховерфлая есть несколько режимов работы, самый простейший это webserver когда в него загружаются симуляции
      # он их просто отдает.
      - "-webserver"
    # Монтируем всю папку hoverfly
    volumes:
      - "./hoverfly:/hoverfly_app:ro"
    ports:
      - 8501:8500
      - 8889:8888