version: "3.8"

services:
  database:
    container_name: postgres
    image: postgres:15.0-alpine
    environment:
      POSTGRES_USER: boris
      POSTGRES_PASSWORD: 12345
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
